### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#10]
I find it strange and inconsistent, that in the case of winning the user gets displayed the wins and directly afterwards is asked to continue or quit,
while not winning needs the user to press a any key to continue
and afterwards press exactly 'y' to really continue
https://github.com/nsofiia/slot_machine/blob/cc84a2905430abaafe79aac3fa996d7f5db758fc/Program.cs#L268-L276

**Comment by nsofiia** [comment]
@incredibleLeitman fixed, ready for review
