### ISSUE TITLE
Why is this an int?

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#13]
https://github.com/nsofiia/slot_machine/blob/ca28bb99fee9a76ec6de9600687f96a899c1b098/Program.cs#L30

You basically just use this value to keep track if the winnings are > 0,
which can also done with a bool

**Comment by nsofiia** [comment]
@incredibleLeitman what is the benefit of using bool instead in this case?

**Comment by incredibleLeitman** [comment]
it is more on point and clearer to read:
You only have two outcomes win or not.  No reason to store numbers or chars or whatever
