### ISSUE TITLE
Do you really need an own, separate function for this?

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#14]
https://github.com/nsofiia/slot_machine/blob/ca28bb99fee9a76ec6de9600687f96a899c1b098/UI.cs#L82-L88

You can embed the Console.Clear statement just in those UI functions where you want to print stuff and want the screen before to be empty 🤷

**Comment by nsofiia** [comment]
@incredibleLeitman Console.Clear() is the one UI option that can stay as is in the code?

**Comment by incredibleLeitman** [comment]
No, Console.Clear but no reason to have a own function for this...

Currently you call it as a separate function like:
```
newScreen(); // clears console
printRules(); // prints the rules
```
or
```
waitForInput(); // program waits for user to enter choice
newScreen();
```

But because printRules or waitForInput are also UI functions, you can embed the Console.Clear call directly in this function.
For example, the first thing printRules does it clearing the console... or the last thing after a valid input is received in waitForInput
