### ISSUE TITLE
Always add a default case for a swtich

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#15]
https://github.com/nsofiia/slot_machine/blob/ca28bb99fee9a76ec6de9600687f96a899c1b098/UI.cs#L166-L175

Although this is no problem now, this might bite you in the future if you or any other developer make changes.
Imagine you add a larger grid, more choices, etc... and you forget to update this function... It is hard to find the error.

On the other hand if you have a default case that just prints "unsupported value <value>" you instantly know, what went wrong and needs to be changed

**Comment by incredibleLeitman** [comment]
Just print "Combination" is not a good default case, because in reality this means, you hit an use case that is not supported by your program 👆 
Better would be to print that an invalid line was tried to be played or even to throw an exception

**Comment by nsofiia** [comment]
@incredibleLeitman 
what would be an example of the use cases like this?

**Comment by incredibleLeitman** [comment]
Assume you have a switch that covers all the possible lines you can play in your slot machine...
for example
```
switch (lines)
    case AllHor:
        ...
    case AllVer:
       ...
    case Center
       ...
    and so on
```

If you have no default case at all, you program will run into "undefined behaviour" because nobody ever tested what happens if you give 12 (or basically anything you don't have in your case) to the method 🤷 

So the first step would be to add a default case to your switch, to even notify that somehing was not planed this way.
But if you now have a default case, that "acts" like this is totally ok this can delay real errors, especially if you then have one okaish default for all unsupported values.

Usually, if you don't support any other value than the ones you defined in your cases, you'd have a default case that prints something like "invalid/unsupported option: --entered value-- " to make two things:
- notify the developer that something is not right -> don't behave like this is all good, this is something that wasn't planed or dont work as intended
- give the developer information about what value was entered -> maybe this value should not be possible? Or it should be handled but someone just forgot to implement the corresponding case? Could even be a copy-paste error or a forgotten break no one noticed
