### ISSUE TITLE
Why are you having an out param?

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#18]
https://github.com/nsofiia/slot_machine/blob/ca28bb99fee9a76ec6de9600687f96a899c1b098/UI.cs#L65-L80

thing about, if you really need an out param for this? why not just return a value?
Especially in this case, you HAVE an out param, but also return the same value.

It seems like you having trouble understanding what the "out" keyword really means, if this is the case, maybe talk about that with Florian in the next call. But usually there are very rare and specific cases, where you really need to use out params.

Also, since this is UI method, do you really need to pass the input?
Check what value you receive in this method when calling it, does it ever change?

**Comment by nsofiia** [comment]
@incredibleLeitman 
`do you really need to pass the input?
Check what value you receive in this method when calling it, does it ever change?`

yes, value can be invalid entry,
this method checks the value, and only assigns the correct one

I added return because it was giving me errors otherwise,
I'll double check

**Comment by incredibleLeitman** [comment]
> this method checks the value, and only assigns the correct one
Yeah but you can just create the input within the function as a local variable, you don't need to provide it.

Is suggest again, that you check what is really coming to you function. Make a Console.WriteLine or use the debugger to watch, what value "input" has, everytime you call the function.

**Comment by incredibleLeitman** [comment]
> "method is simplified"
is not a good commit message... instead you should write WHICH method was modified and HOW
for example: "remove out param and input from getCorrectValue"

Git commit messages should also be written in present, a good schema is
"when i will pull this commit it will <commit message>"

**Comment by nsofiia** [comment]
@incredibleLeitman woah! it is definitely better way, thank you
