### ISSUE TITLE
Unnecessary continue?

### ISSUE THREAD

**Issue by f-rakete** [nsofiia/slot_machine#3]
https://github.com/nsofiia/slot_machine/blob/83034b1099247c1f499f8f068661beff252f7c1f/Program.cs#L59
After this statement, nothing happens in the loop anyway - is the continue statement needed?

**Comment by incredibleLeitman** [comment]
same applies here
https://github.com/nsofiia/slot_machine/blob/cc84a2905430abaafe79aac3fa996d7f5db758fc/Program.cs#L283

**Comment by incredibleLeitman** [comment]
There is still and unnecessary continue at the end of your loop

https://github.com/nsofiia/slot_machine/blob/ca28bb99fee9a76ec6de9600687f96a899c1b098/Program.cs#L215-L223

**Comment by nsofiia** [comment]
@incredibleLeitman 
I have more than one now :) 
still need to remove one of them? to me they are looking ok.
<img width="562" alt="Screen Shot 2022-12-18 at 5 20 04 PM" src="https://user-images.githubusercontent.com/88280676/208324777-e5e884f6-cb38-43cf-81ce-176e0cc66660.png">

**Comment by incredibleLeitman** [comment]
The return statement is ok 👍 

The problem was "continue" which had done essentially nothing:
A loop just runs again if you dont break or return, 
so writing continue makes no sense, because the loop continues anyway 🤷
