### ISSUE TITLE
.Rank does not do what you think it does

### ISSUE THREAD

**Issue by f-rakete** [nsofiia/slot_machine#4]
https://github.com/nsofiia/slot_machine/blob/83034b1099247c1f499f8f068661beff252f7c1f/Program.cs#L70-L72

Please don't assume some properties do what you expect, always read the documentation to make sure you understand what it does.
![image](https://user-images.githubusercontent.com/69428398/206686457-fae43586-d32e-48d1-9665-84e631f6fbaf.png)

.Rank just tells you how many dimensions an array has. It doesnt make sense as a limit for your for loops

**Comment by nsofiia** [comment]
@f-rakete 
here I am using Rank number to get "2", 
since this is how many dimensions I have and this is where index count stops.
it is shorter 
(slotMachine.Rank) = 2 
vs    
(slotMachine.Length - 1) = 2

Why is it not a good practice?

**Comment by f-rakete** [comment]
because that's just the dimension of the array, not the size. 
Length also does work differently than you obviously expect with multidimensional arrays. please take some time to read the docs.

rank gives you 2 because you have 2 dimensions. But if you would have a 4x4 grid (or any other size) it woudlnt work.

length gives you the total amaount of values, which is 9 in a 3x3 gird.

check out this => https://stackoverflow.com/questions/4260207/how-do-you-get-the-width-and-height-of-a-multi-dimensional-array


what youre doing is "bad practice" because you just think "i need a 2" without thinking why you need it

**Comment by nsofiia** [comment]
@f-rakete thank you :)
