### ISSUE TITLE
Format integers when used as double to indicate the design

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#7]
When using double datatype for integer values its good practice to show them as floating point values so that readers can see that is intentional.

When I see
```double val = 5;``` 
I immediately assume that this should be an int.

So to counteract this you can ```double val = 5.0;``` or use the 'd' or 'D' suffix like ```double val = 5d;```

To print those values you can make use of specialized string formatting or use standard numeric format strings:
https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings
Especially the currency would fit your you bet values

**Comment by nsofiia** [comment]
@incredibleLeitman fixed, ready for review
