### ISSUE TITLE
If having only having one condition that breaks your loop you should use it

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/slot_machine#8]
When you have a loop, that only "runs until x" you should definitely use exactly this condition as termination to make the code more intuitive and readable.

You could rewrite this
https://github.com/nsofiia/slot_machine/blob/cc84a2905430abaafe79aac3fa996d7f5db758fc/Program.cs#L66-L78

to this
```
line_choise = Char.ToUpper(Console.ReadKey().KeyChar);
//checks if input is anything but a letter, if not, repeats
while (!playChoices.Contains(line_choise))
{
  Console.WriteLine("\nChoose one of the letters above.\n");
  line_choise = Char.ToUpper(Console.ReadKey().KeyChar);
}
```
which is more clear to read (I think) but it is also a bit shorter ^^

If you don't like the double "  line_choise = Char.ToUpper(Console.ReadKey().KeyChar);" line
you could instead put the user prompt in an condition:
```
line_choise = ' '; // start with an invalid, empty choice
//checks if input is anything but a letter, if not, repeats
while (!playChoices.Contains(line_choise))
{
  line_choise = Char.ToUpper(Console.ReadKey().KeyChar);
  if (!playChoices.Contains(line_choise))
  {
      Console.WriteLine("\nChoose one of the letters above.\n");
  }
}
```

Also I just noticed, that the comment in this code does not match the code below 👆

**Comment by nsofiia** [comment]
@incredibleLeitman fixed, ready for review
